Vagrant.configure(2) do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
    aws.keypair_name = "vagrant"

    aws.ami = "ami-a21529cc"
    aws.instance_type = "t2.micro"
    aws.security_groups = [ 'sg-d14df5b4']
    aws.region = "ap-northeast-1"
    aws.terminate_on_shutdown = true
    aws.subnet_id = 'subnet-04e23c73'
    aws.elastic_ip  = true
    aws.associate_public_ip = true

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/vagrant.pem"
  end
end
